// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Permission extends pulumi.CustomResource {
    /**
     * Get an existing Permission resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PermissionState, opts?: pulumi.CustomResourceOptions): Permission {
        return new Permission(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'britive:index/permission:Permission';

    /**
     * Returns true if the given object is an instance of Permission.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Permission {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Permission.__pulumiType;
    }

    /**
     * Actions to be performed on the resource
     */
    public readonly actions!: pulumi.Output<string[]>;
    /**
     * The consumer service
     */
    public readonly consumer!: pulumi.Output<string>;
    /**
     * The description of the Britive permission
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The name of Britive permission
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Comma separated list of resources
     */
    public readonly resources!: pulumi.Output<string[]>;

    /**
     * Create a Permission resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PermissionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PermissionArgs | PermissionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PermissionState | undefined;
            resourceInputs["actions"] = state ? state.actions : undefined;
            resourceInputs["consumer"] = state ? state.consumer : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["resources"] = state ? state.resources : undefined;
        } else {
            const args = argsOrState as PermissionArgs | undefined;
            if ((!args || args.actions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'actions'");
            }
            if ((!args || args.consumer === undefined) && !opts.urn) {
                throw new Error("Missing required property 'consumer'");
            }
            if ((!args || args.resources === undefined) && !opts.urn) {
                throw new Error("Missing required property 'resources'");
            }
            resourceInputs["actions"] = args ? args.actions : undefined;
            resourceInputs["consumer"] = args ? args.consumer : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["resources"] = args ? args.resources : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Permission.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Permission resources.
 */
export interface PermissionState {
    /**
     * Actions to be performed on the resource
     */
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The consumer service
     */
    consumer?: pulumi.Input<string>;
    /**
     * The description of the Britive permission
     */
    description?: pulumi.Input<string>;
    /**
     * The name of Britive permission
     */
    name?: pulumi.Input<string>;
    /**
     * Comma separated list of resources
     */
    resources?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Permission resource.
 */
export interface PermissionArgs {
    /**
     * Actions to be performed on the resource
     */
    actions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The consumer service
     */
    consumer: pulumi.Input<string>;
    /**
     * The description of the Britive permission
     */
    description?: pulumi.Input<string>;
    /**
     * The name of Britive permission
     */
    name?: pulumi.Input<string>;
    /**
     * Comma separated list of resources
     */
    resources: pulumi.Input<pulumi.Input<string>[]>;
}
