// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSshkey(args?: GetSshkeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSshkeyResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("transip:index/getSshkey:getSshkey", {
        "description": args.description,
        "id": args.id,
        "key": args.key,
        "md5Fingerprint": args.md5Fingerprint,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSshkey.
 */
export interface GetSshkeyArgs {
    description?: string;
    id?: string;
    key?: string;
    md5Fingerprint?: string;
}

/**
 * A collection of values returned by getSshkey.
 */
export interface GetSshkeyResult {
    readonly description?: string;
    readonly id?: string;
    readonly key?: string;
    readonly md5Fingerprint?: string;
}
export function getSshkeyOutput(args?: GetSshkeyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSshkeyResult> {
    return pulumi.output(args).apply((a: any) => getSshkey(a, opts))
}

/**
 * A collection of arguments for invoking getSshkey.
 */
export interface GetSshkeyOutputArgs {
    description?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    key?: pulumi.Input<string>;
    md5Fingerprint?: pulumi.Input<string>;
}
