// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCiscoSigCredentialsFeatureTemplate(args?: GetCiscoSigCredentialsFeatureTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetCiscoSigCredentialsFeatureTemplateResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sdwan:index/getCiscoSigCredentialsFeatureTemplate:getCiscoSigCredentialsFeatureTemplate", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCiscoSigCredentialsFeatureTemplate.
 */
export interface GetCiscoSigCredentialsFeatureTemplateArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getCiscoSigCredentialsFeatureTemplate.
 */
export interface GetCiscoSigCredentialsFeatureTemplateResult {
    readonly description: string;
    readonly deviceTypes: string[];
    readonly id: string;
    readonly name: string;
    readonly templateType: string;
    readonly umbrellaApiKey: string;
    readonly umbrellaApiKeyVariable: string;
    readonly umbrellaApiSecret: string;
    readonly umbrellaApiSecretVariable: string;
    readonly umbrellaOrganizationId: string;
    readonly umbrellaOrganizationIdVariable: string;
    readonly version: number;
    readonly zscalerCloudName: number;
    readonly zscalerCloudNameVariable: string;
    readonly zscalerOrganization: string;
    readonly zscalerOrganizationVariable: string;
    readonly zscalerPartnerApiKey: string;
    readonly zscalerPartnerApiKeyVariable: string;
    readonly zscalerPartnerBaseUri: string;
    readonly zscalerPartnerBaseUriVariable: string;
    readonly zscalerPartnerPassword: string;
    readonly zscalerPartnerPasswordVariable: string;
    readonly zscalerPartnerUsername: string;
    readonly zscalerPartnerUsernameVariable: string;
    readonly zscalerPassword: string;
    readonly zscalerPasswordVariable: string;
    readonly zscalerUsername: string;
    readonly zscalerUsernameVariable: string;
}
export function getCiscoSigCredentialsFeatureTemplateOutput(args?: GetCiscoSigCredentialsFeatureTemplateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCiscoSigCredentialsFeatureTemplateResult> {
    return pulumi.output(args).apply((a: any) => getCiscoSigCredentialsFeatureTemplate(a, opts))
}

/**
 * A collection of arguments for invoking getCiscoSigCredentialsFeatureTemplate.
 */
export interface GetCiscoSigCredentialsFeatureTemplateOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
