// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPlatformPipelineList(args: GetPlatformPipelineListArgs, opts?: pulumi.InvokeOptions): Promise<GetPlatformPipelineListResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harness:index/getPlatformPipelineList:getPlatformPipelineList", {
        "id": args.id,
        "identifier": args.identifier,
        "limit": args.limit,
        "name": args.name,
        "orgId": args.orgId,
        "page": args.page,
        "projectId": args.projectId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPlatformPipelineList.
 */
export interface GetPlatformPipelineListArgs {
    id?: string;
    identifier?: string;
    limit?: number;
    name?: string;
    orgId: string;
    page?: number;
    projectId: string;
}

/**
 * A collection of values returned by getPlatformPipelineList.
 */
export interface GetPlatformPipelineListResult {
    readonly description: string;
    readonly id: string;
    readonly identifier?: string;
    readonly limit?: number;
    readonly name?: string;
    readonly orgId: string;
    readonly page?: number;
    readonly pipelines: outputs.GetPlatformPipelineListPipeline[];
    readonly projectId: string;
    readonly tags: string[];
}
export function getPlatformPipelineListOutput(args: GetPlatformPipelineListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPlatformPipelineListResult> {
    return pulumi.output(args).apply((a: any) => getPlatformPipelineList(a, opts))
}

/**
 * A collection of arguments for invoking getPlatformPipelineList.
 */
export interface GetPlatformPipelineListOutputArgs {
    id?: pulumi.Input<string>;
    identifier?: pulumi.Input<string>;
    limit?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    orgId: pulumi.Input<string>;
    page?: pulumi.Input<number>;
    projectId: pulumi.Input<string>;
}
