// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVpcKeepalive(args?: GetVpcKeepaliveArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcKeepaliveResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nxos:index/getVpcKeepalive:getVpcKeepalive", {
        "device": args.device,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVpcKeepalive.
 */
export interface GetVpcKeepaliveArgs {
    device?: string;
}

/**
 * A collection of values returned by getVpcKeepalive.
 */
export interface GetVpcKeepaliveResult {
    readonly destinationIp: string;
    readonly device?: string;
    readonly flushTimeout: number;
    readonly id: string;
    readonly interval: number;
    readonly precedenceType: number;
    readonly precedenceValue: number;
    readonly sourceIp: string;
    readonly timeout: number;
    readonly typeOfServiceByte: number;
    readonly typeOfServiceConfigurationType: number;
    readonly typeOfServiceType: number;
    readonly typeOfServiceValue: number;
    readonly udpPort: number;
    readonly vrf: string;
}
export function getVpcKeepaliveOutput(args?: GetVpcKeepaliveOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVpcKeepaliveResult> {
    return pulumi.output(args).apply((a: any) => getVpcKeepalive(a, opts))
}

/**
 * A collection of arguments for invoking getVpcKeepalive.
 */
export interface GetVpcKeepaliveOutputArgs {
    device?: pulumi.Input<string>;
}
