// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CmlRunnerTimeouts {
    create?: string;
    delete?: string;
    update?: string;
}

export interface MachineTimeouts {
    create?: string;
    delete?: string;
}

export interface TaskStorage {
    container?: string;
    containerOpts?: {[key: string]: string};
    excludes?: string[];
    output?: string;
    workdir?: string;
}

export interface TaskTimeouts {
    create?: string;
    delete?: string;
    read?: string;
    update?: string;
}

