// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDatabaseVmClusterUpdate(args: GetDatabaseVmClusterUpdateArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabaseVmClusterUpdateResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("oci:index/getDatabaseVmClusterUpdate:getDatabaseVmClusterUpdate", {
        "id": args.id,
        "updateId": args.updateId,
        "vmClusterId": args.vmClusterId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDatabaseVmClusterUpdate.
 */
export interface GetDatabaseVmClusterUpdateArgs {
    id?: string;
    updateId: string;
    vmClusterId: string;
}

/**
 * A collection of values returned by getDatabaseVmClusterUpdate.
 */
export interface GetDatabaseVmClusterUpdateResult {
    readonly availableActions: string[];
    readonly description: string;
    readonly id: string;
    readonly lastAction: string;
    readonly lifecycleDetails: string;
    readonly state: string;
    readonly timeReleased: string;
    readonly updateId: string;
    readonly updateType: string;
    readonly version: string;
    readonly vmClusterId: string;
}
export function getDatabaseVmClusterUpdateOutput(args: GetDatabaseVmClusterUpdateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabaseVmClusterUpdateResult> {
    return pulumi.output(args).apply((a: any) => getDatabaseVmClusterUpdate(a, opts))
}

/**
 * A collection of arguments for invoking getDatabaseVmClusterUpdate.
 */
export interface GetDatabaseVmClusterUpdateOutputArgs {
    id?: pulumi.Input<string>;
    updateId: pulumi.Input<string>;
    vmClusterId: pulumi.Input<string>;
}
