// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabaseManagementManagedDatabaseAddmTasks(args: GetDatabaseManagementManagedDatabaseAddmTasksArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabaseManagementManagedDatabaseAddmTasksResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("oci:index/getDatabaseManagementManagedDatabaseAddmTasks:getDatabaseManagementManagedDatabaseAddmTasks", {
        "filters": args.filters,
        "id": args.id,
        "managedDatabaseId": args.managedDatabaseId,
        "timeEnd": args.timeEnd,
        "timeStart": args.timeStart,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDatabaseManagementManagedDatabaseAddmTasks.
 */
export interface GetDatabaseManagementManagedDatabaseAddmTasksArgs {
    filters?: inputs.GetDatabaseManagementManagedDatabaseAddmTasksFilter[];
    id?: string;
    managedDatabaseId: string;
    timeEnd: string;
    timeStart: string;
}

/**
 * A collection of values returned by getDatabaseManagementManagedDatabaseAddmTasks.
 */
export interface GetDatabaseManagementManagedDatabaseAddmTasksResult {
    readonly addmTasksCollections: outputs.GetDatabaseManagementManagedDatabaseAddmTasksAddmTasksCollection[];
    readonly filters?: outputs.GetDatabaseManagementManagedDatabaseAddmTasksFilter[];
    readonly id: string;
    readonly managedDatabaseId: string;
    readonly timeEnd: string;
    readonly timeStart: string;
}
export function getDatabaseManagementManagedDatabaseAddmTasksOutput(args: GetDatabaseManagementManagedDatabaseAddmTasksOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabaseManagementManagedDatabaseAddmTasksResult> {
    return pulumi.output(args).apply((a: any) => getDatabaseManagementManagedDatabaseAddmTasks(a, opts))
}

/**
 * A collection of arguments for invoking getDatabaseManagementManagedDatabaseAddmTasks.
 */
export interface GetDatabaseManagementManagedDatabaseAddmTasksOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetDatabaseManagementManagedDatabaseAddmTasksFilterArgs>[]>;
    id?: pulumi.Input<string>;
    managedDatabaseId: pulumi.Input<string>;
    timeEnd: pulumi.Input<string>;
    timeStart: pulumi.Input<string>;
}
