// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getFusionAppsFusionEnvironmentServiceAttachments(args: GetFusionAppsFusionEnvironmentServiceAttachmentsArgs, opts?: pulumi.InvokeOptions): Promise<GetFusionAppsFusionEnvironmentServiceAttachmentsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("oci:index/getFusionAppsFusionEnvironmentServiceAttachments:getFusionAppsFusionEnvironmentServiceAttachments", {
        "displayName": args.displayName,
        "filters": args.filters,
        "fusionEnvironmentId": args.fusionEnvironmentId,
        "id": args.id,
        "serviceInstanceType": args.serviceInstanceType,
        "state": args.state,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getFusionAppsFusionEnvironmentServiceAttachments.
 */
export interface GetFusionAppsFusionEnvironmentServiceAttachmentsArgs {
    displayName?: string;
    filters?: inputs.GetFusionAppsFusionEnvironmentServiceAttachmentsFilter[];
    fusionEnvironmentId: string;
    id?: string;
    serviceInstanceType?: string;
    state?: string;
}

/**
 * A collection of values returned by getFusionAppsFusionEnvironmentServiceAttachments.
 */
export interface GetFusionAppsFusionEnvironmentServiceAttachmentsResult {
    readonly displayName?: string;
    readonly filters?: outputs.GetFusionAppsFusionEnvironmentServiceAttachmentsFilter[];
    readonly fusionEnvironmentId: string;
    readonly id: string;
    readonly serviceAttachmentCollections: outputs.GetFusionAppsFusionEnvironmentServiceAttachmentsServiceAttachmentCollection[];
    readonly serviceInstanceType?: string;
    readonly state?: string;
}
export function getFusionAppsFusionEnvironmentServiceAttachmentsOutput(args: GetFusionAppsFusionEnvironmentServiceAttachmentsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFusionAppsFusionEnvironmentServiceAttachmentsResult> {
    return pulumi.output(args).apply((a: any) => getFusionAppsFusionEnvironmentServiceAttachments(a, opts))
}

/**
 * A collection of arguments for invoking getFusionAppsFusionEnvironmentServiceAttachments.
 */
export interface GetFusionAppsFusionEnvironmentServiceAttachmentsOutputArgs {
    displayName?: pulumi.Input<string>;
    filters?: pulumi.Input<pulumi.Input<inputs.GetFusionAppsFusionEnvironmentServiceAttachmentsFilterArgs>[]>;
    fusionEnvironmentId: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    serviceInstanceType?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
}
