// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NetworkManagerStaticMember extends pulumi.CustomResource {
    /**
     * Get an existing NetworkManagerStaticMember resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkManagerStaticMemberState, opts?: pulumi.CustomResourceOptions): NetworkManagerStaticMember {
        return new NetworkManagerStaticMember(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azurerm:index/networkManagerStaticMember:NetworkManagerStaticMember';

    /**
     * Returns true if the given object is an instance of NetworkManagerStaticMember.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkManagerStaticMember {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkManagerStaticMember.__pulumiType;
    }

    public readonly name!: pulumi.Output<string>;
    public readonly networkGroupId!: pulumi.Output<string>;
    public /*out*/ readonly region!: pulumi.Output<string>;
    public readonly targetVirtualNetworkId!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.NetworkManagerStaticMemberTimeouts | undefined>;

    /**
     * Create a NetworkManagerStaticMember resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkManagerStaticMemberArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkManagerStaticMemberArgs | NetworkManagerStaticMemberState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkManagerStaticMemberState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkGroupId"] = state ? state.networkGroupId : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["targetVirtualNetworkId"] = state ? state.targetVirtualNetworkId : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as NetworkManagerStaticMemberArgs | undefined;
            if ((!args || args.networkGroupId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'networkGroupId'");
            }
            if ((!args || args.targetVirtualNetworkId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'targetVirtualNetworkId'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkGroupId"] = args ? args.networkGroupId : undefined;
            resourceInputs["targetVirtualNetworkId"] = args ? args.targetVirtualNetworkId : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["region"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkManagerStaticMember.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering NetworkManagerStaticMember resources.
 */
export interface NetworkManagerStaticMemberState {
    name?: pulumi.Input<string>;
    networkGroupId?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    targetVirtualNetworkId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkManagerStaticMemberTimeouts>;
}

/**
 * The set of arguments for constructing a NetworkManagerStaticMember resource.
 */
export interface NetworkManagerStaticMemberArgs {
    name?: pulumi.Input<string>;
    networkGroupId: pulumi.Input<string>;
    targetVirtualNetworkId: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkManagerStaticMemberTimeouts>;
}
