// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAllowedProtocolsTacacs(args?: GetAllowedProtocolsTacacsArgs, opts?: pulumi.InvokeOptions): Promise<GetAllowedProtocolsTacacsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ise:index/getAllowedProtocolsTacacs:getAllowedProtocolsTacacs", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAllowedProtocolsTacacs.
 */
export interface GetAllowedProtocolsTacacsArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getAllowedProtocolsTacacs.
 */
export interface GetAllowedProtocolsTacacsResult {
    readonly allowChap: boolean;
    readonly allowMsChapV1: boolean;
    readonly allowPapAscii: boolean;
    readonly description: string;
    readonly id: string;
    readonly name: string;
}
export function getAllowedProtocolsTacacsOutput(args?: GetAllowedProtocolsTacacsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAllowedProtocolsTacacsResult> {
    return pulumi.output(args).apply((a: any) => getAllowedProtocolsTacacs(a, opts))
}

/**
 * A collection of arguments for invoking getAllowedProtocolsTacacs.
 */
export interface GetAllowedProtocolsTacacsOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
