// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPartnerintegrationEtl(args?: GetPartnerintegrationEtlArgs, opts?: pulumi.InvokeOptions): Promise<GetPartnerintegrationEtlResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("intersight:index/getPartnerintegrationEtl:getPartnerintegrationEtl", {
        "accountMoid": args.accountMoid,
        "additionalProperties": args.additionalProperties,
        "ancestors": args.ancestors,
        "classId": args.classId,
        "createTime": args.createTime,
        "data": args.data,
        "domainGroupMoid": args.domainGroupMoid,
        "id": args.id,
        "inventory": args.inventory,
        "modTime": args.modTime,
        "moid": args.moid,
        "name": args.name,
        "objectType": args.objectType,
        "owners": args.owners,
        "parent": args.parent,
        "permissionResources": args.permissionResources,
        "sharedScope": args.sharedScope,
        "tags": args.tags,
        "versionContext": args.versionContext,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPartnerintegrationEtl.
 */
export interface GetPartnerintegrationEtlArgs {
    accountMoid?: string;
    additionalProperties?: string;
    ancestors?: inputs.GetPartnerintegrationEtlAncestor[];
    classId?: string;
    createTime?: string;
    data?: string;
    domainGroupMoid?: string;
    id?: string;
    inventory?: inputs.GetPartnerintegrationEtlInventory;
    modTime?: string;
    moid?: string;
    name?: string;
    objectType?: string;
    owners?: string[];
    parent?: inputs.GetPartnerintegrationEtlParent;
    permissionResources?: inputs.GetPartnerintegrationEtlPermissionResource[];
    sharedScope?: string;
    tags?: inputs.GetPartnerintegrationEtlTag[];
    versionContext?: inputs.GetPartnerintegrationEtlVersionContext;
}

/**
 * A collection of values returned by getPartnerintegrationEtl.
 */
export interface GetPartnerintegrationEtlResult {
    readonly accountMoid?: string;
    readonly additionalProperties?: string;
    readonly ancestors?: outputs.GetPartnerintegrationEtlAncestor[];
    readonly classId?: string;
    readonly createTime?: string;
    readonly data?: string;
    readonly domainGroupMoid?: string;
    readonly id: string;
    readonly inventory?: outputs.GetPartnerintegrationEtlInventory;
    readonly modTime?: string;
    readonly moid?: string;
    readonly name?: string;
    readonly objectType?: string;
    readonly owners?: string[];
    readonly parent?: outputs.GetPartnerintegrationEtlParent;
    readonly permissionResources?: outputs.GetPartnerintegrationEtlPermissionResource[];
    readonly results: outputs.GetPartnerintegrationEtlResult[];
    readonly sharedScope?: string;
    readonly tags?: outputs.GetPartnerintegrationEtlTag[];
    readonly versionContext?: outputs.GetPartnerintegrationEtlVersionContext;
}
export function getPartnerintegrationEtlOutput(args?: GetPartnerintegrationEtlOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPartnerintegrationEtlResult> {
    return pulumi.output(args).apply((a: any) => getPartnerintegrationEtl(a, opts))
}

/**
 * A collection of arguments for invoking getPartnerintegrationEtl.
 */
export interface GetPartnerintegrationEtlOutputArgs {
    accountMoid?: pulumi.Input<string>;
    additionalProperties?: pulumi.Input<string>;
    ancestors?: pulumi.Input<pulumi.Input<inputs.GetPartnerintegrationEtlAncestorArgs>[]>;
    classId?: pulumi.Input<string>;
    createTime?: pulumi.Input<string>;
    data?: pulumi.Input<string>;
    domainGroupMoid?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    inventory?: pulumi.Input<inputs.GetPartnerintegrationEtlInventoryArgs>;
    modTime?: pulumi.Input<string>;
    moid?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    objectType?: pulumi.Input<string>;
    owners?: pulumi.Input<pulumi.Input<string>[]>;
    parent?: pulumi.Input<inputs.GetPartnerintegrationEtlParentArgs>;
    permissionResources?: pulumi.Input<pulumi.Input<inputs.GetPartnerintegrationEtlPermissionResourceArgs>[]>;
    sharedScope?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<inputs.GetPartnerintegrationEtlTagArgs>[]>;
    versionContext?: pulumi.Input<inputs.GetPartnerintegrationEtlVersionContextArgs>;
}
