// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRuleSets(args?: GetRuleSetsArgs, opts?: pulumi.InvokeOptions): Promise<GetRuleSetsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("illumio-core:index/getRuleSets:getRuleSets", {
        "description": args.description,
        "externalDataReference": args.externalDataReference,
        "externalDataSet": args.externalDataSet,
        "id": args.id,
        "labels": args.labels,
        "matchType": args.matchType,
        "maxResults": args.maxResults,
        "name": args.name,
        "pversion": args.pversion,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRuleSets.
 */
export interface GetRuleSetsArgs {
    description?: string;
    externalDataReference?: string;
    externalDataSet?: string;
    id?: string;
    labels?: string;
    matchType?: string;
    maxResults?: string;
    name?: string;
    pversion?: string;
}

/**
 * A collection of values returned by getRuleSets.
 */
export interface GetRuleSetsResult {
    readonly description?: string;
    readonly externalDataReference?: string;
    readonly externalDataSet?: string;
    readonly id: string;
    readonly items: outputs.GetRuleSetsItem[];
    readonly labels?: string;
    readonly matchType?: string;
    readonly maxResults?: string;
    readonly name?: string;
    readonly pversion?: string;
}
export function getRuleSetsOutput(args?: GetRuleSetsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRuleSetsResult> {
    return pulumi.output(args).apply((a: any) => getRuleSets(a, opts))
}

/**
 * A collection of arguments for invoking getRuleSets.
 */
export interface GetRuleSetsOutputArgs {
    description?: pulumi.Input<string>;
    externalDataReference?: pulumi.Input<string>;
    externalDataSet?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    labels?: pulumi.Input<string>;
    matchType?: pulumi.Input<string>;
    maxResults?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    pversion?: pulumi.Input<string>;
}
