// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBgpAddressFamilyIpv4(args: GetBgpAddressFamilyIpv4Args, opts?: pulumi.InvokeOptions): Promise<GetBgpAddressFamilyIpv4Result> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("iosxe:index/getBgpAddressFamilyIpv4:getBgpAddressFamilyIpv4", {
        "afName": args.afName,
        "asn": args.asn,
        "device": args.device,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBgpAddressFamilyIpv4.
 */
export interface GetBgpAddressFamilyIpv4Args {
    afName: string;
    asn: string;
    device?: string;
}

/**
 * A collection of values returned by getBgpAddressFamilyIpv4.
 */
export interface GetBgpAddressFamilyIpv4Result {
    readonly afName: string;
    readonly asn: string;
    readonly device?: string;
    readonly id: string;
    readonly ipv4UnicastAggregateAddresses: outputs.GetBgpAddressFamilyIpv4Ipv4UnicastAggregateAddress[];
    readonly ipv4UnicastNetworks: outputs.GetBgpAddressFamilyIpv4Ipv4UnicastNetwork[];
    readonly ipv4UnicastNetworksMasks: outputs.GetBgpAddressFamilyIpv4Ipv4UnicastNetworksMask[];
    readonly ipv4UnicastRedistributeConnected: boolean;
    readonly ipv4UnicastRedistributeStatic: boolean;
}
export function getBgpAddressFamilyIpv4Output(args: GetBgpAddressFamilyIpv4OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBgpAddressFamilyIpv4Result> {
    return pulumi.output(args).apply((a: any) => getBgpAddressFamilyIpv4(a, opts))
}

/**
 * A collection of arguments for invoking getBgpAddressFamilyIpv4.
 */
export interface GetBgpAddressFamilyIpv4OutputArgs {
    afName: pulumi.Input<string>;
    asn: pulumi.Input<string>;
    device?: pulumi.Input<string>;
}
