// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPortGroupObjects(args: GetPortGroupObjectsArgs, opts?: pulumi.InvokeOptions): Promise<GetPortGroupObjectsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fmc:index/getPortGroupObjects:getPortGroupObjects", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPortGroupObjects.
 */
export interface GetPortGroupObjectsArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getPortGroupObjects.
 */
export interface GetPortGroupObjectsResult {
    readonly id: string;
    readonly name: string;
}
export function getPortGroupObjectsOutput(args: GetPortGroupObjectsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPortGroupObjectsResult> {
    return pulumi.output(args).apply((a: any) => getPortGroupObjects(a, opts))
}

/**
 * A collection of arguments for invoking getPortGroupObjects.
 */
export interface GetPortGroupObjectsOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
