// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SwitchigmpsnoopingGlobals extends pulumi.CustomResource {
    /**
     * Get an existing SwitchigmpsnoopingGlobals resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SwitchigmpsnoopingGlobalsState, opts?: pulumi.CustomResourceOptions): SwitchigmpsnoopingGlobals {
        return new SwitchigmpsnoopingGlobals(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fortiswitch:index/switchigmpsnoopingGlobals:SwitchigmpsnoopingGlobals';

    /**
     * Returns true if the given object is an instance of SwitchigmpsnoopingGlobals.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SwitchigmpsnoopingGlobals {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SwitchigmpsnoopingGlobals.__pulumiType;
    }

    public readonly agingTime!: pulumi.Output<number>;
    public readonly leaveResponseTimeout!: pulumi.Output<number>;
    public readonly proxyReportInterval!: pulumi.Output<number>;
    public readonly queryInterval!: pulumi.Output<number>;
    public readonly queryMaxResponseTimeout!: pulumi.Output<number>;

    /**
     * Create a SwitchigmpsnoopingGlobals resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SwitchigmpsnoopingGlobalsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SwitchigmpsnoopingGlobalsArgs | SwitchigmpsnoopingGlobalsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SwitchigmpsnoopingGlobalsState | undefined;
            resourceInputs["agingTime"] = state ? state.agingTime : undefined;
            resourceInputs["leaveResponseTimeout"] = state ? state.leaveResponseTimeout : undefined;
            resourceInputs["proxyReportInterval"] = state ? state.proxyReportInterval : undefined;
            resourceInputs["queryInterval"] = state ? state.queryInterval : undefined;
            resourceInputs["queryMaxResponseTimeout"] = state ? state.queryMaxResponseTimeout : undefined;
        } else {
            const args = argsOrState as SwitchigmpsnoopingGlobalsArgs | undefined;
            resourceInputs["agingTime"] = args ? args.agingTime : undefined;
            resourceInputs["leaveResponseTimeout"] = args ? args.leaveResponseTimeout : undefined;
            resourceInputs["proxyReportInterval"] = args ? args.proxyReportInterval : undefined;
            resourceInputs["queryInterval"] = args ? args.queryInterval : undefined;
            resourceInputs["queryMaxResponseTimeout"] = args ? args.queryMaxResponseTimeout : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SwitchigmpsnoopingGlobals.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SwitchigmpsnoopingGlobals resources.
 */
export interface SwitchigmpsnoopingGlobalsState {
    agingTime?: pulumi.Input<number>;
    leaveResponseTimeout?: pulumi.Input<number>;
    proxyReportInterval?: pulumi.Input<number>;
    queryInterval?: pulumi.Input<number>;
    queryMaxResponseTimeout?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a SwitchigmpsnoopingGlobals resource.
 */
export interface SwitchigmpsnoopingGlobalsArgs {
    agingTime?: pulumi.Input<number>;
    leaveResponseTimeout?: pulumi.Input<number>;
    proxyReportInterval?: pulumi.Input<number>;
    queryInterval?: pulumi.Input<number>;
    queryMaxResponseTimeout?: pulumi.Input<number>;
}
