// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Cacheselector extends pulumi.CustomResource {
    /**
     * Get an existing Cacheselector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CacheselectorState, opts?: pulumi.CustomResourceOptions): Cacheselector {
        return new Cacheselector(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'citrixadc:index/cacheselector:Cacheselector';

    /**
     * Returns true if the given object is an instance of Cacheselector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cacheselector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cacheselector.__pulumiType;
    }

    public readonly rules!: pulumi.Output<string[]>;
    public readonly selectorname!: pulumi.Output<string>;

    /**
     * Create a Cacheselector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CacheselectorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CacheselectorArgs | CacheselectorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CacheselectorState | undefined;
            resourceInputs["rules"] = state ? state.rules : undefined;
            resourceInputs["selectorname"] = state ? state.selectorname : undefined;
        } else {
            const args = argsOrState as CacheselectorArgs | undefined;
            if ((!args || args.rules === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            if ((!args || args.selectorname === undefined) && !opts.urn) {
                throw new Error("Missing required property 'selectorname'");
            }
            resourceInputs["rules"] = args ? args.rules : undefined;
            resourceInputs["selectorname"] = args ? args.selectorname : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cacheselector.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Cacheselector resources.
 */
export interface CacheselectorState {
    rules?: pulumi.Input<pulumi.Input<string>[]>;
    selectorname?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Cacheselector resource.
 */
export interface CacheselectorArgs {
    rules: pulumi.Input<pulumi.Input<string>[]>;
    selectorname: pulumi.Input<string>;
}
