// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSessionApplicationPolicy(opts?: pulumi.InvokeOptions): Promise<GetSessionApplicationPolicyResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pingfederate:index/getSessionApplicationPolicy:getSessionApplicationPolicy", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSessionApplicationPolicy.
 */
export interface GetSessionApplicationPolicyResult {
    readonly id: string;
    readonly idleTimeoutMins: number;
    readonly maxTimeoutMins: number;
}
export function getSessionApplicationPolicyOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetSessionApplicationPolicyResult> {
    return pulumi.output(getSessionApplicationPolicy(opts))
}
