// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BeyondcorpAppConnector extends pulumi.CustomResource {
    /**
     * Get an existing BeyondcorpAppConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BeyondcorpAppConnectorState, opts?: pulumi.CustomResourceOptions): BeyondcorpAppConnector {
        return new BeyondcorpAppConnector(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'google:index/beyondcorpAppConnector:BeyondcorpAppConnector';

    /**
     * Returns true if the given object is an instance of BeyondcorpAppConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BeyondcorpAppConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BeyondcorpAppConnector.__pulumiType;
    }

    /**
     * An arbitrary user-provided name for the AppConnector.
     */
    public readonly displayName!: pulumi.Output<string | undefined>;
    public /*out*/ readonly effectiveLabels!: pulumi.Output<{[key: string]: string}>;
    /**
     * Resource labels to represent user provided metadata. **Note**: This field is non-authoritative, and will only manage the
     * labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels present on the
     * resource.
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * ID of the AppConnector.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Principal information about the Identity of the AppConnector.
     */
    public readonly principalInfo!: pulumi.Output<outputs.BeyondcorpAppConnectorPrincipalInfo>;
    public readonly project!: pulumi.Output<string>;
    /**
     * The region of the AppConnector.
     */
    public readonly region!: pulumi.Output<string | undefined>;
    /**
     * Represents the different states of a AppConnector.
     */
    public /*out*/ readonly state!: pulumi.Output<string>;
    /**
     * The combination of labels configured directly on the resource and default labels configured on the provider.
     */
    public /*out*/ readonly terraformLabels!: pulumi.Output<{[key: string]: string}>;
    public readonly timeouts!: pulumi.Output<outputs.BeyondcorpAppConnectorTimeouts | undefined>;

    /**
     * Create a BeyondcorpAppConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BeyondcorpAppConnectorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BeyondcorpAppConnectorArgs | BeyondcorpAppConnectorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BeyondcorpAppConnectorState | undefined;
            resourceInputs["displayName"] = state ? state.displayName : undefined;
            resourceInputs["effectiveLabels"] = state ? state.effectiveLabels : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["principalInfo"] = state ? state.principalInfo : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["terraformLabels"] = state ? state.terraformLabels : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as BeyondcorpAppConnectorArgs | undefined;
            if ((!args || args.principalInfo === undefined) && !opts.urn) {
                throw new Error("Missing required property 'principalInfo'");
            }
            resourceInputs["displayName"] = args ? args.displayName : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["principalInfo"] = args ? args.principalInfo : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["effectiveLabels"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["terraformLabels"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BeyondcorpAppConnector.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BeyondcorpAppConnector resources.
 */
export interface BeyondcorpAppConnectorState {
    /**
     * An arbitrary user-provided name for the AppConnector.
     */
    displayName?: pulumi.Input<string>;
    effectiveLabels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Resource labels to represent user provided metadata. **Note**: This field is non-authoritative, and will only manage the
     * labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels present on the
     * resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * ID of the AppConnector.
     */
    name?: pulumi.Input<string>;
    /**
     * Principal information about the Identity of the AppConnector.
     */
    principalInfo?: pulumi.Input<inputs.BeyondcorpAppConnectorPrincipalInfo>;
    project?: pulumi.Input<string>;
    /**
     * The region of the AppConnector.
     */
    region?: pulumi.Input<string>;
    /**
     * Represents the different states of a AppConnector.
     */
    state?: pulumi.Input<string>;
    /**
     * The combination of labels configured directly on the resource and default labels configured on the provider.
     */
    terraformLabels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.BeyondcorpAppConnectorTimeouts>;
}

/**
 * The set of arguments for constructing a BeyondcorpAppConnector resource.
 */
export interface BeyondcorpAppConnectorArgs {
    /**
     * An arbitrary user-provided name for the AppConnector.
     */
    displayName?: pulumi.Input<string>;
    /**
     * Resource labels to represent user provided metadata. **Note**: This field is non-authoritative, and will only manage the
     * labels present in your configuration. Please refer to the field 'effective_labels' for all of the labels present on the
     * resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * ID of the AppConnector.
     */
    name?: pulumi.Input<string>;
    /**
     * Principal information about the Identity of the AppConnector.
     */
    principalInfo: pulumi.Input<inputs.BeyondcorpAppConnectorPrincipalInfo>;
    project?: pulumi.Input<string>;
    /**
     * The region of the AppConnector.
     */
    region?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.BeyondcorpAppConnectorTimeouts>;
}
