// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOrgIdpGithubEs(args: GetOrgIdpGithubEsArgs, opts?: pulumi.InvokeOptions): Promise<GetOrgIdpGithubEsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zitadel:index/getOrgIdpGithubEs:getOrgIdpGithubEs", {
        "id": args.id,
        "orgId": args.orgId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOrgIdpGithubEs.
 */
export interface GetOrgIdpGithubEsArgs {
    id: string;
    orgId?: string;
}

/**
 * A collection of values returned by getOrgIdpGithubEs.
 */
export interface GetOrgIdpGithubEsResult {
    readonly authorizationEndpoint: string;
    readonly clientId: string;
    readonly clientSecret: string;
    readonly id: string;
    readonly isAutoCreation: boolean;
    readonly isAutoUpdate: boolean;
    readonly isCreationAllowed: boolean;
    readonly isLinkingAllowed: boolean;
    readonly name: string;
    readonly orgId?: string;
    readonly scopes: string[];
    readonly tokenEndpoint: string;
    readonly userEndpoint: string;
}
export function getOrgIdpGithubEsOutput(args: GetOrgIdpGithubEsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOrgIdpGithubEsResult> {
    return pulumi.output(args).apply((a: any) => getOrgIdpGithubEs(a, opts))
}

/**
 * A collection of arguments for invoking getOrgIdpGithubEs.
 */
export interface GetOrgIdpGithubEsOutputArgs {
    id: pulumi.Input<string>;
    orgId?: pulumi.Input<string>;
}
