// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMonitoringMeshIstioService(args: GetMonitoringMeshIstioServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetMonitoringMeshIstioServiceResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("google-beta:index/getMonitoringMeshIstioService:getMonitoringMeshIstioService", {
        "id": args.id,
        "meshUid": args.meshUid,
        "project": args.project,
        "serviceName": args.serviceName,
        "serviceNamespace": args.serviceNamespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMonitoringMeshIstioService.
 */
export interface GetMonitoringMeshIstioServiceArgs {
    id?: string;
    meshUid: string;
    project?: string;
    serviceName: string;
    serviceNamespace: string;
}

/**
 * A collection of values returned by getMonitoringMeshIstioService.
 */
export interface GetMonitoringMeshIstioServiceResult {
    readonly displayName: string;
    readonly id: string;
    readonly meshUid: string;
    readonly name: string;
    readonly project?: string;
    readonly serviceId: string;
    readonly serviceName: string;
    readonly serviceNamespace: string;
    readonly telemetries: outputs.GetMonitoringMeshIstioServiceTelemetry[];
    readonly userLabels: {[key: string]: string};
}
export function getMonitoringMeshIstioServiceOutput(args: GetMonitoringMeshIstioServiceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMonitoringMeshIstioServiceResult> {
    return pulumi.output(args).apply((a: any) => getMonitoringMeshIstioService(a, opts))
}

/**
 * A collection of arguments for invoking getMonitoringMeshIstioService.
 */
export interface GetMonitoringMeshIstioServiceOutputArgs {
    id?: pulumi.Input<string>;
    meshUid: pulumi.Input<string>;
    project?: pulumi.Input<string>;
    serviceName: pulumi.Input<string>;
    serviceNamespace: pulumi.Input<string>;
}
