// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOauthProfileAccessLevelGroupMsgVpnAccessLevelException(args: GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionArgs, opts?: pulumi.InvokeOptions): Promise<GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solacebrokerappliance:index/getOauthProfileAccessLevelGroupMsgVpnAccessLevelException:getOauthProfileAccessLevelGroupMsgVpnAccessLevelException", {
        "groupName": args.groupName,
        "msgVpnName": args.msgVpnName,
        "oauthProfileName": args.oauthProfileName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOauthProfileAccessLevelGroupMsgVpnAccessLevelException.
 */
export interface GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionArgs {
    groupName: string;
    msgVpnName: string;
    oauthProfileName: string;
}

/**
 * A collection of values returned by getOauthProfileAccessLevelGroupMsgVpnAccessLevelException.
 */
export interface GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionResult {
    readonly accessLevel: string;
    readonly groupName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly msgVpnName: string;
    readonly oauthProfileName: string;
}
export function getOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionOutput(args: GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionResult> {
    return pulumi.output(args).apply((a: any) => getOauthProfileAccessLevelGroupMsgVpnAccessLevelException(a, opts))
}

/**
 * A collection of arguments for invoking getOauthProfileAccessLevelGroupMsgVpnAccessLevelException.
 */
export interface GetOauthProfileAccessLevelGroupMsgVpnAccessLevelExceptionOutputArgs {
    groupName: pulumi.Input<string>;
    msgVpnName: pulumi.Input<string>;
    oauthProfileName: pulumi.Input<string>;
}
