// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ObjectWanoptProfileHttp extends pulumi.CustomResource {
    /**
     * Get an existing ObjectWanoptProfileHttp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ObjectWanoptProfileHttpState, opts?: pulumi.CustomResourceOptions): ObjectWanoptProfileHttp {
        return new ObjectWanoptProfileHttp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fortimanager:index/objectWanoptProfileHttp:ObjectWanoptProfileHttp';

    /**
     * Returns true if the given object is an instance of ObjectWanoptProfileHttp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ObjectWanoptProfileHttp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ObjectWanoptProfileHttp.__pulumiType;
    }

    public readonly adom!: pulumi.Output<string | undefined>;
    public readonly byteCaching!: pulumi.Output<string>;
    public readonly logTraffic!: pulumi.Output<string>;
    public readonly ports!: pulumi.Output<number[]>;
    public readonly preferChunking!: pulumi.Output<string>;
    public readonly profile!: pulumi.Output<string>;
    public readonly protocolOpt!: pulumi.Output<string>;
    public readonly scopetype!: pulumi.Output<string | undefined>;
    public readonly secureTunnel!: pulumi.Output<string>;
    public readonly ssl!: pulumi.Output<string>;
    public readonly sslPorts!: pulumi.Output<number[]>;
    public readonly status!: pulumi.Output<string>;
    public readonly tunnelNonHttp!: pulumi.Output<string | undefined>;
    public readonly tunnelSharing!: pulumi.Output<string>;
    public readonly unknownHttpVersion!: pulumi.Output<string | undefined>;

    /**
     * Create a ObjectWanoptProfileHttp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ObjectWanoptProfileHttpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ObjectWanoptProfileHttpArgs | ObjectWanoptProfileHttpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ObjectWanoptProfileHttpState | undefined;
            resourceInputs["adom"] = state ? state.adom : undefined;
            resourceInputs["byteCaching"] = state ? state.byteCaching : undefined;
            resourceInputs["logTraffic"] = state ? state.logTraffic : undefined;
            resourceInputs["ports"] = state ? state.ports : undefined;
            resourceInputs["preferChunking"] = state ? state.preferChunking : undefined;
            resourceInputs["profile"] = state ? state.profile : undefined;
            resourceInputs["protocolOpt"] = state ? state.protocolOpt : undefined;
            resourceInputs["scopetype"] = state ? state.scopetype : undefined;
            resourceInputs["secureTunnel"] = state ? state.secureTunnel : undefined;
            resourceInputs["ssl"] = state ? state.ssl : undefined;
            resourceInputs["sslPorts"] = state ? state.sslPorts : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["tunnelNonHttp"] = state ? state.tunnelNonHttp : undefined;
            resourceInputs["tunnelSharing"] = state ? state.tunnelSharing : undefined;
            resourceInputs["unknownHttpVersion"] = state ? state.unknownHttpVersion : undefined;
        } else {
            const args = argsOrState as ObjectWanoptProfileHttpArgs | undefined;
            if ((!args || args.profile === undefined) && !opts.urn) {
                throw new Error("Missing required property 'profile'");
            }
            resourceInputs["adom"] = args ? args.adom : undefined;
            resourceInputs["byteCaching"] = args ? args.byteCaching : undefined;
            resourceInputs["logTraffic"] = args ? args.logTraffic : undefined;
            resourceInputs["ports"] = args ? args.ports : undefined;
            resourceInputs["preferChunking"] = args ? args.preferChunking : undefined;
            resourceInputs["profile"] = args ? args.profile : undefined;
            resourceInputs["protocolOpt"] = args ? args.protocolOpt : undefined;
            resourceInputs["scopetype"] = args ? args.scopetype : undefined;
            resourceInputs["secureTunnel"] = args ? args.secureTunnel : undefined;
            resourceInputs["ssl"] = args ? args.ssl : undefined;
            resourceInputs["sslPorts"] = args ? args.sslPorts : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
            resourceInputs["tunnelNonHttp"] = args ? args.tunnelNonHttp : undefined;
            resourceInputs["tunnelSharing"] = args ? args.tunnelSharing : undefined;
            resourceInputs["unknownHttpVersion"] = args ? args.unknownHttpVersion : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ObjectWanoptProfileHttp.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ObjectWanoptProfileHttp resources.
 */
export interface ObjectWanoptProfileHttpState {
    adom?: pulumi.Input<string>;
    byteCaching?: pulumi.Input<string>;
    logTraffic?: pulumi.Input<string>;
    ports?: pulumi.Input<pulumi.Input<number>[]>;
    preferChunking?: pulumi.Input<string>;
    profile?: pulumi.Input<string>;
    protocolOpt?: pulumi.Input<string>;
    scopetype?: pulumi.Input<string>;
    secureTunnel?: pulumi.Input<string>;
    ssl?: pulumi.Input<string>;
    sslPorts?: pulumi.Input<pulumi.Input<number>[]>;
    status?: pulumi.Input<string>;
    tunnelNonHttp?: pulumi.Input<string>;
    tunnelSharing?: pulumi.Input<string>;
    unknownHttpVersion?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ObjectWanoptProfileHttp resource.
 */
export interface ObjectWanoptProfileHttpArgs {
    adom?: pulumi.Input<string>;
    byteCaching?: pulumi.Input<string>;
    logTraffic?: pulumi.Input<string>;
    ports?: pulumi.Input<pulumi.Input<number>[]>;
    preferChunking?: pulumi.Input<string>;
    profile: pulumi.Input<string>;
    protocolOpt?: pulumi.Input<string>;
    scopetype?: pulumi.Input<string>;
    secureTunnel?: pulumi.Input<string>;
    ssl?: pulumi.Input<string>;
    sslPorts?: pulumi.Input<pulumi.Input<number>[]>;
    status?: pulumi.Input<string>;
    tunnelNonHttp?: pulumi.Input<string>;
    tunnelSharing?: pulumi.Input<string>;
    unknownHttpVersion?: pulumi.Input<string>;
}
