// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy extends pulumi.CustomResource {
    /**
     * Get an existing DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyState, opts?: pulumi.CustomResourceOptions): DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy {
        return new DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thunder:index/ddosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy:DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy';

    /**
     * Returns true if the given object is an instance of DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy.__pulumiType;
    }

    /**
     * 'bypass': Always permit for the Source to bypass all feature & limit checks; 'deny': Blacklist incoming packets for
     * service;
     */
    public readonly action!: pulumi.Output<string | undefined>;
    /**
     * ClassListName
     */
    public readonly classListName!: pulumi.Output<string>;
    /**
     * 'configuration': Configure overflow policy for class-list;
     */
    public readonly dummyName!: pulumi.Output<string>;
    /**
     * Global limit ID
     */
    public readonly glid!: pulumi.Output<string | undefined>;
    /**
     * Enable logging
     */
    public readonly logEnable!: pulumi.Output<number | undefined>;
    /**
     * Enable log periodic
     */
    public readonly logPeriodic!: pulumi.Output<number | undefined>;
    /**
     * PortNum
     */
    public readonly portNum!: pulumi.Output<string>;
    /**
     * Protocol
     */
    public readonly protocol!: pulumi.Output<string>;
    /**
     * SrcBasedPolicyName
     */
    public readonly srcBasedPolicyName!: pulumi.Output<string>;
    /**
     * Customized tag
     */
    public readonly userTag!: pulumi.Output<string | undefined>;
    /**
     * uuid of the object
     */
    public readonly uuid!: pulumi.Output<string>;
    /**
     * ZoneName
     */
    public readonly zoneName!: pulumi.Output<string>;
    public readonly zoneTemplate!: pulumi.Output<outputs.DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyZoneTemplate | undefined>;

    /**
     * Create a DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyArgs | DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyState | undefined;
            resourceInputs["action"] = state ? state.action : undefined;
            resourceInputs["classListName"] = state ? state.classListName : undefined;
            resourceInputs["dummyName"] = state ? state.dummyName : undefined;
            resourceInputs["glid"] = state ? state.glid : undefined;
            resourceInputs["logEnable"] = state ? state.logEnable : undefined;
            resourceInputs["logPeriodic"] = state ? state.logPeriodic : undefined;
            resourceInputs["portNum"] = state ? state.portNum : undefined;
            resourceInputs["protocol"] = state ? state.protocol : undefined;
            resourceInputs["srcBasedPolicyName"] = state ? state.srcBasedPolicyName : undefined;
            resourceInputs["userTag"] = state ? state.userTag : undefined;
            resourceInputs["uuid"] = state ? state.uuid : undefined;
            resourceInputs["zoneName"] = state ? state.zoneName : undefined;
            resourceInputs["zoneTemplate"] = state ? state.zoneTemplate : undefined;
        } else {
            const args = argsOrState as DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyArgs | undefined;
            if ((!args || args.classListName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'classListName'");
            }
            if ((!args || args.dummyName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dummyName'");
            }
            if ((!args || args.portNum === undefined) && !opts.urn) {
                throw new Error("Missing required property 'portNum'");
            }
            if ((!args || args.protocol === undefined) && !opts.urn) {
                throw new Error("Missing required property 'protocol'");
            }
            if ((!args || args.srcBasedPolicyName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'srcBasedPolicyName'");
            }
            if ((!args || args.zoneName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneName'");
            }
            resourceInputs["action"] = args ? args.action : undefined;
            resourceInputs["classListName"] = args ? args.classListName : undefined;
            resourceInputs["dummyName"] = args ? args.dummyName : undefined;
            resourceInputs["glid"] = args ? args.glid : undefined;
            resourceInputs["logEnable"] = args ? args.logEnable : undefined;
            resourceInputs["logPeriodic"] = args ? args.logPeriodic : undefined;
            resourceInputs["portNum"] = args ? args.portNum : undefined;
            resourceInputs["protocol"] = args ? args.protocol : undefined;
            resourceInputs["srcBasedPolicyName"] = args ? args.srcBasedPolicyName : undefined;
            resourceInputs["userTag"] = args ? args.userTag : undefined;
            resourceInputs["uuid"] = args ? args.uuid : undefined;
            resourceInputs["zoneName"] = args ? args.zoneName : undefined;
            resourceInputs["zoneTemplate"] = args ? args.zoneTemplate : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy resources.
 */
export interface DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyState {
    /**
     * 'bypass': Always permit for the Source to bypass all feature & limit checks; 'deny': Blacklist incoming packets for
     * service;
     */
    action?: pulumi.Input<string>;
    /**
     * ClassListName
     */
    classListName?: pulumi.Input<string>;
    /**
     * 'configuration': Configure overflow policy for class-list;
     */
    dummyName?: pulumi.Input<string>;
    /**
     * Global limit ID
     */
    glid?: pulumi.Input<string>;
    /**
     * Enable logging
     */
    logEnable?: pulumi.Input<number>;
    /**
     * Enable log periodic
     */
    logPeriodic?: pulumi.Input<number>;
    /**
     * PortNum
     */
    portNum?: pulumi.Input<string>;
    /**
     * Protocol
     */
    protocol?: pulumi.Input<string>;
    /**
     * SrcBasedPolicyName
     */
    srcBasedPolicyName?: pulumi.Input<string>;
    /**
     * Customized tag
     */
    userTag?: pulumi.Input<string>;
    /**
     * uuid of the object
     */
    uuid?: pulumi.Input<string>;
    /**
     * ZoneName
     */
    zoneName?: pulumi.Input<string>;
    zoneTemplate?: pulumi.Input<inputs.DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyZoneTemplate>;
}

/**
 * The set of arguments for constructing a DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicy resource.
 */
export interface DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyArgs {
    /**
     * 'bypass': Always permit for the Source to bypass all feature & limit checks; 'deny': Blacklist incoming packets for
     * service;
     */
    action?: pulumi.Input<string>;
    /**
     * ClassListName
     */
    classListName: pulumi.Input<string>;
    /**
     * 'configuration': Configure overflow policy for class-list;
     */
    dummyName: pulumi.Input<string>;
    /**
     * Global limit ID
     */
    glid?: pulumi.Input<string>;
    /**
     * Enable logging
     */
    logEnable?: pulumi.Input<number>;
    /**
     * Enable log periodic
     */
    logPeriodic?: pulumi.Input<number>;
    /**
     * PortNum
     */
    portNum: pulumi.Input<string>;
    /**
     * Protocol
     */
    protocol: pulumi.Input<string>;
    /**
     * SrcBasedPolicyName
     */
    srcBasedPolicyName: pulumi.Input<string>;
    /**
     * Customized tag
     */
    userTag?: pulumi.Input<string>;
    /**
     * uuid of the object
     */
    uuid?: pulumi.Input<string>;
    /**
     * ZoneName
     */
    zoneName: pulumi.Input<string>;
    zoneTemplate?: pulumi.Input<inputs.DdosDstZonePortZoneServiceSrcBasedPolicyPolicyClassListClassListOverflowPolicyZoneTemplate>;
}
