// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCgnv6OneToOneSharedPoolGroupOper(args?: GetCgnv6OneToOneSharedPoolGroupOperArgs, opts?: pulumi.InvokeOptions): Promise<GetCgnv6OneToOneSharedPoolGroupOperResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("thunder:index/getCgnv6OneToOneSharedPoolGroupOper:getCgnv6OneToOneSharedPoolGroupOper", {
        "id": args.id,
        "members": args.members,
        "oper": args.oper,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCgnv6OneToOneSharedPoolGroupOper.
 */
export interface GetCgnv6OneToOneSharedPoolGroupOperArgs {
    id?: string;
    members?: inputs.GetCgnv6OneToOneSharedPoolGroupOperMembers;
    oper?: inputs.GetCgnv6OneToOneSharedPoolGroupOperOper;
}

/**
 * A collection of values returned by getCgnv6OneToOneSharedPoolGroupOper.
 */
export interface GetCgnv6OneToOneSharedPoolGroupOperResult {
    readonly id: string;
    readonly members?: outputs.GetCgnv6OneToOneSharedPoolGroupOperMembers;
    readonly oper?: outputs.GetCgnv6OneToOneSharedPoolGroupOperOper;
}
export function getCgnv6OneToOneSharedPoolGroupOperOutput(args?: GetCgnv6OneToOneSharedPoolGroupOperOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCgnv6OneToOneSharedPoolGroupOperResult> {
    return pulumi.output(args).apply((a: any) => getCgnv6OneToOneSharedPoolGroupOper(a, opts))
}

/**
 * A collection of arguments for invoking getCgnv6OneToOneSharedPoolGroupOper.
 */
export interface GetCgnv6OneToOneSharedPoolGroupOperOutputArgs {
    id?: pulumi.Input<string>;
    members?: pulumi.Input<inputs.GetCgnv6OneToOneSharedPoolGroupOperMembersArgs>;
    oper?: pulumi.Input<inputs.GetCgnv6OneToOneSharedPoolGroupOperOperArgs>;
}
