// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getScaleoutDebugHashTableOper(args?: GetScaleoutDebugHashTableOperArgs, opts?: pulumi.InvokeOptions): Promise<GetScaleoutDebugHashTableOperResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("thunder:index/getScaleoutDebugHashTableOper:getScaleoutDebugHashTableOper", {
        "id": args.id,
        "oper": args.oper,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScaleoutDebugHashTableOper.
 */
export interface GetScaleoutDebugHashTableOperArgs {
    id?: string;
    oper?: inputs.GetScaleoutDebugHashTableOperOper;
}

/**
 * A collection of values returned by getScaleoutDebugHashTableOper.
 */
export interface GetScaleoutDebugHashTableOperResult {
    readonly id: string;
    readonly oper?: outputs.GetScaleoutDebugHashTableOperOper;
}
export function getScaleoutDebugHashTableOperOutput(args?: GetScaleoutDebugHashTableOperOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetScaleoutDebugHashTableOperResult> {
    return pulumi.output(args).apply((a: any) => getScaleoutDebugHashTableOper(a, opts))
}

/**
 * A collection of arguments for invoking getScaleoutDebugHashTableOper.
 */
export interface GetScaleoutDebugHashTableOperOutputArgs {
    id?: pulumi.Input<string>;
    oper?: pulumi.Input<inputs.GetScaleoutDebugHashTableOperOperArgs>;
}
