// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSchemaSiteAnpEpgStaticLeaf(args: GetSchemaSiteAnpEpgStaticLeafArgs, opts?: pulumi.InvokeOptions): Promise<GetSchemaSiteAnpEpgStaticLeafResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mso:index/getSchemaSiteAnpEpgStaticLeaf:getSchemaSiteAnpEpgStaticLeaf", {
        "anpName": args.anpName,
        "epgName": args.epgName,
        "id": args.id,
        "path": args.path,
        "schemaId": args.schemaId,
        "siteId": args.siteId,
        "templateName": args.templateName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSchemaSiteAnpEpgStaticLeaf.
 */
export interface GetSchemaSiteAnpEpgStaticLeafArgs {
    anpName: string;
    epgName: string;
    id?: string;
    path: string;
    schemaId: string;
    siteId: string;
    templateName: string;
}

/**
 * A collection of values returned by getSchemaSiteAnpEpgStaticLeaf.
 */
export interface GetSchemaSiteAnpEpgStaticLeafResult {
    readonly anpName: string;
    readonly epgName: string;
    readonly id: string;
    readonly path: string;
    readonly portEncapVlan: number;
    readonly schemaId: string;
    readonly siteId: string;
    readonly templateName: string;
}
export function getSchemaSiteAnpEpgStaticLeafOutput(args: GetSchemaSiteAnpEpgStaticLeafOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSchemaSiteAnpEpgStaticLeafResult> {
    return pulumi.output(args).apply((a: any) => getSchemaSiteAnpEpgStaticLeaf(a, opts))
}

/**
 * A collection of arguments for invoking getSchemaSiteAnpEpgStaticLeaf.
 */
export interface GetSchemaSiteAnpEpgStaticLeafOutputArgs {
    anpName: pulumi.Input<string>;
    epgName: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    path: pulumi.Input<string>;
    schemaId: pulumi.Input<string>;
    siteId: pulumi.Input<string>;
    templateName: pulumi.Input<string>;
}
