// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPipeline(args: GetPipelineArgs, opts?: pulumi.InvokeOptions): Promise<GetPipelineResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("buildkite:index/getPipeline:getPipeline", {
        "slug": args.slug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPipeline.
 */
export interface GetPipelineArgs {
    slug: string;
}

/**
 * A collection of values returned by getPipeline.
 */
export interface GetPipelineResult {
    readonly defaultBranch: string;
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly repository: string;
    readonly slug: string;
    readonly uuid: string;
    readonly webhookUrl: string;
}
export function getPipelineOutput(args: GetPipelineOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPipelineResult> {
    return pulumi.output(args).apply((a: any) => getPipeline(a, opts))
}

/**
 * A collection of arguments for invoking getPipeline.
 */
export interface GetPipelineOutputArgs {
    slug: pulumi.Input<string>;
}
