// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getWafcrs(args?: GetWafcrsArgs, opts?: pulumi.InvokeOptions): Promise<GetWafcrsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("avi:index/getWafcrs:getWafcrs", {
        "id": args.id,
        "name": args.name,
        "tenantRef": args.tenantRef,
        "uuid": args.uuid,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWafcrs.
 */
export interface GetWafcrsArgs {
    id?: string;
    name?: string;
    tenantRef?: string;
    uuid?: string;
}

/**
 * A collection of values returned by getWafcrs.
 */
export interface GetWafcrsResult {
    readonly allowedRequestContentTypeCharsets: string[];
    readonly configpbAttributes: outputs.GetWafcrsConfigpbAttribute[];
    readonly description: string;
    readonly files: outputs.GetWafcrsFile[];
    readonly groups: outputs.GetWafcrsGroup[];
    readonly id: string;
    readonly integrity: string;
    readonly integrityValues: string[];
    readonly markers: outputs.GetWafcrsMarker[];
    readonly name: string;
    readonly releaseDate: string;
    readonly restrictedExtensions: string[];
    readonly restrictedHeaders: string[];
    readonly tenantRef: string;
    readonly uuid: string;
    readonly version: string;
}
export function getWafcrsOutput(args?: GetWafcrsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetWafcrsResult> {
    return pulumi.output(args).apply((a: any) => getWafcrs(a, opts))
}

/**
 * A collection of arguments for invoking getWafcrs.
 */
export interface GetWafcrsOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    tenantRef?: pulumi.Input<string>;
    uuid?: pulumi.Input<string>;
}
