// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCodeconnectionsConnections(opts?: pulumi.InvokeOptions): Promise<GetCodeconnectionsConnectionsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("awscc:index/getCodeconnectionsConnections:getCodeconnectionsConnections", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getCodeconnectionsConnections.
 */
export interface GetCodeconnectionsConnectionsResult {
    readonly id: string;
    readonly ids: string[];
}
export function getCodeconnectionsConnectionsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetCodeconnectionsConnectionsResult> {
    return pulumi.output(getCodeconnectionsConnections(opts))
}
