// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRdsDbClusterParameterGroup(args: GetRdsDbClusterParameterGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRdsDbClusterParameterGroupResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("awscc:index/getRdsDbClusterParameterGroup:getRdsDbClusterParameterGroup", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRdsDbClusterParameterGroup.
 */
export interface GetRdsDbClusterParameterGroupArgs {
    id: string;
}

/**
 * A collection of values returned by getRdsDbClusterParameterGroup.
 */
export interface GetRdsDbClusterParameterGroupResult {
    readonly dbClusterParameterGroupName: string;
    readonly description: string;
    readonly family: string;
    readonly id: string;
    readonly parameters: string;
    readonly tags: outputs.GetRdsDbClusterParameterGroupTag[];
}
export function getRdsDbClusterParameterGroupOutput(args: GetRdsDbClusterParameterGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRdsDbClusterParameterGroupResult> {
    return pulumi.output(args).apply((a: any) => getRdsDbClusterParameterGroup(a, opts))
}

/**
 * A collection of arguments for invoking getRdsDbClusterParameterGroup.
 */
export interface GetRdsDbClusterParameterGroupOutputArgs {
    id: pulumi.Input<string>;
}
