// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSupportappAccountAliases(opts?: pulumi.InvokeOptions): Promise<GetSupportappAccountAliasesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("awscc:index/getSupportappAccountAliases:getSupportappAccountAliases", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSupportappAccountAliases.
 */
export interface GetSupportappAccountAliasesResult {
    readonly id: string;
    readonly ids: string[];
}
export function getSupportappAccountAliasesOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetSupportappAccountAliasesResult> {
    return pulumi.output(getSupportappAccountAliases(opts))
}
