// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class KendrarankingExecutionPlan extends pulumi.CustomResource {
    /**
     * Get an existing KendrarankingExecutionPlan resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KendrarankingExecutionPlanState, opts?: pulumi.CustomResourceOptions): KendrarankingExecutionPlan {
        return new KendrarankingExecutionPlan(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'awscc:index/kendrarankingExecutionPlan:KendrarankingExecutionPlan';

    /**
     * Returns true if the given object is an instance of KendrarankingExecutionPlan.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KendrarankingExecutionPlan {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KendrarankingExecutionPlan.__pulumiType;
    }

    public /*out*/ readonly arn!: pulumi.Output<string>;
    /**
     * Capacity units
     */
    public readonly capacityUnits!: pulumi.Output<outputs.KendrarankingExecutionPlanCapacityUnits>;
    /**
     * A description for the execution plan
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * Unique ID of rescore execution plan
     */
    public /*out*/ readonly executionPlanId!: pulumi.Output<string>;
    /**
     * Name of kendra ranking rescore execution plan
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Tags for labeling the execution plan
     */
    public readonly tags!: pulumi.Output<outputs.KendrarankingExecutionPlanTag[]>;

    /**
     * Create a KendrarankingExecutionPlan resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KendrarankingExecutionPlanArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KendrarankingExecutionPlanArgs | KendrarankingExecutionPlanState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KendrarankingExecutionPlanState | undefined;
            resourceInputs["arn"] = state ? state.arn : undefined;
            resourceInputs["capacityUnits"] = state ? state.capacityUnits : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["executionPlanId"] = state ? state.executionPlanId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as KendrarankingExecutionPlanArgs | undefined;
            resourceInputs["capacityUnits"] = args ? args.capacityUnits : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["executionPlanId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KendrarankingExecutionPlan.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering KendrarankingExecutionPlan resources.
 */
export interface KendrarankingExecutionPlanState {
    arn?: pulumi.Input<string>;
    /**
     * Capacity units
     */
    capacityUnits?: pulumi.Input<inputs.KendrarankingExecutionPlanCapacityUnits>;
    /**
     * A description for the execution plan
     */
    description?: pulumi.Input<string>;
    /**
     * Unique ID of rescore execution plan
     */
    executionPlanId?: pulumi.Input<string>;
    /**
     * Name of kendra ranking rescore execution plan
     */
    name?: pulumi.Input<string>;
    /**
     * Tags for labeling the execution plan
     */
    tags?: pulumi.Input<pulumi.Input<inputs.KendrarankingExecutionPlanTag>[]>;
}

/**
 * The set of arguments for constructing a KendrarankingExecutionPlan resource.
 */
export interface KendrarankingExecutionPlanArgs {
    /**
     * Capacity units
     */
    capacityUnits?: pulumi.Input<inputs.KendrarankingExecutionPlanCapacityUnits>;
    /**
     * A description for the execution plan
     */
    description?: pulumi.Input<string>;
    /**
     * Name of kendra ranking rescore execution plan
     */
    name?: pulumi.Input<string>;
    /**
     * Tags for labeling the execution plan
     */
    tags?: pulumi.Input<pulumi.Input<inputs.KendrarankingExecutionPlanTag>[]>;
}
