// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAmi(args?: GetAmiArgs, opts?: pulumi.InvokeOptions): Promise<GetAmiResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws:index/getAmi:getAmi", {
        "executableUsers": args.executableUsers,
        "filters": args.filters,
        "id": args.id,
        "includeDeprecated": args.includeDeprecated,
        "mostRecent": args.mostRecent,
        "nameRegex": args.nameRegex,
        "owners": args.owners,
        "tags": args.tags,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAmi.
 */
export interface GetAmiArgs {
    executableUsers?: string[];
    filters?: inputs.GetAmiFilter[];
    id?: string;
    includeDeprecated?: boolean;
    mostRecent?: boolean;
    nameRegex?: string;
    owners?: string[];
    tags?: {[key: string]: string};
    timeouts?: inputs.GetAmiTimeouts;
}

/**
 * A collection of values returned by getAmi.
 */
export interface GetAmiResult {
    readonly architecture: string;
    readonly arn: string;
    readonly blockDeviceMappings: outputs.GetAmiBlockDeviceMapping[];
    readonly bootMode: string;
    readonly creationDate: string;
    readonly deprecationTime: string;
    readonly description: string;
    readonly enaSupport: boolean;
    readonly executableUsers?: string[];
    readonly filters?: outputs.GetAmiFilter[];
    readonly hypervisor: string;
    readonly id: string;
    readonly imageId: string;
    readonly imageLocation: string;
    readonly imageOwnerAlias: string;
    readonly imageType: string;
    readonly imdsSupport: string;
    readonly includeDeprecated?: boolean;
    readonly kernelId: string;
    readonly mostRecent?: boolean;
    readonly name: string;
    readonly nameRegex?: string;
    readonly ownerId: string;
    readonly owners?: string[];
    readonly platform: string;
    readonly platformDetails: string;
    readonly productCodes: outputs.GetAmiProductCode[];
    readonly public: boolean;
    readonly ramdiskId: string;
    readonly rootDeviceName: string;
    readonly rootDeviceType: string;
    readonly rootSnapshotId: string;
    readonly sriovNetSupport: string;
    readonly state: string;
    readonly stateReason: {[key: string]: string};
    readonly tags: {[key: string]: string};
    readonly timeouts?: outputs.GetAmiTimeouts;
    readonly tpmSupport: string;
    readonly usageOperation: string;
    readonly virtualizationType: string;
}
export function getAmiOutput(args?: GetAmiOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAmiResult> {
    return pulumi.output(args).apply((a: any) => getAmi(a, opts))
}

/**
 * A collection of arguments for invoking getAmi.
 */
export interface GetAmiOutputArgs {
    executableUsers?: pulumi.Input<pulumi.Input<string>[]>;
    filters?: pulumi.Input<pulumi.Input<inputs.GetAmiFilterArgs>[]>;
    id?: pulumi.Input<string>;
    includeDeprecated?: pulumi.Input<boolean>;
    mostRecent?: pulumi.Input<boolean>;
    nameRegex?: pulumi.Input<string>;
    owners?: pulumi.Input<pulumi.Input<string>[]>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.GetAmiTimeoutsArgs>;
}
