// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationIamBinding extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationIamBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationIamBindingState, opts?: pulumi.CustomResourceOptions): OrganizationIamBinding {
        return new OrganizationIamBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'hcp:index/organizationIamBinding:OrganizationIamBinding';

    /**
     * Returns true if the given object is an instance of OrganizationIamBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationIamBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationIamBinding.__pulumiType;
    }

    /**
     * The principal to bind to the given role.
     */
    public readonly principalId!: pulumi.Output<string>;
    /**
     * The role name to bind to the given principal.
     */
    public readonly role!: pulumi.Output<string>;

    /**
     * Create a OrganizationIamBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationIamBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationIamBindingArgs | OrganizationIamBindingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationIamBindingState | undefined;
            resourceInputs["principalId"] = state ? state.principalId : undefined;
            resourceInputs["role"] = state ? state.role : undefined;
        } else {
            const args = argsOrState as OrganizationIamBindingArgs | undefined;
            if ((!args || args.principalId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'principalId'");
            }
            if ((!args || args.role === undefined) && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["principalId"] = args ? args.principalId : undefined;
            resourceInputs["role"] = args ? args.role : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrganizationIamBinding.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationIamBinding resources.
 */
export interface OrganizationIamBindingState {
    /**
     * The principal to bind to the given role.
     */
    principalId?: pulumi.Input<string>;
    /**
     * The role name to bind to the given principal.
     */
    role?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a OrganizationIamBinding resource.
 */
export interface OrganizationIamBindingArgs {
    /**
     * The principal to bind to the given role.
     */
    principalId: pulumi.Input<string>;
    /**
     * The role name to bind to the given principal.
     */
    role: pulumi.Input<string>;
}
