// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEmrDiskTypes(args: GetEmrDiskTypesArgs, opts?: pulumi.InvokeOptions): Promise<GetEmrDiskTypesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:index/getEmrDiskTypes:getEmrDiskTypes", {
        "clusterType": args.clusterType,
        "destinationResource": args.destinationResource,
        "id": args.id,
        "instanceChargeType": args.instanceChargeType,
        "instanceType": args.instanceType,
        "outputFile": args.outputFile,
        "zoneId": args.zoneId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEmrDiskTypes.
 */
export interface GetEmrDiskTypesArgs {
    clusterType: string;
    destinationResource: string;
    id?: string;
    instanceChargeType: string;
    instanceType: string;
    outputFile?: string;
    zoneId?: string;
}

/**
 * A collection of values returned by getEmrDiskTypes.
 */
export interface GetEmrDiskTypesResult {
    readonly clusterType: string;
    readonly destinationResource: string;
    readonly id: string;
    readonly ids: string[];
    readonly instanceChargeType: string;
    readonly instanceType: string;
    readonly outputFile?: string;
    readonly types: outputs.GetEmrDiskTypesType[];
    readonly zoneId?: string;
}
export function getEmrDiskTypesOutput(args: GetEmrDiskTypesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetEmrDiskTypesResult> {
    return pulumi.output(args).apply((a: any) => getEmrDiskTypes(a, opts))
}

/**
 * A collection of arguments for invoking getEmrDiskTypes.
 */
export interface GetEmrDiskTypesOutputArgs {
    clusterType: pulumi.Input<string>;
    destinationResource: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    instanceChargeType: pulumi.Input<string>;
    instanceType: pulumi.Input<string>;
    outputFile?: pulumi.Input<string>;
    zoneId?: pulumi.Input<string>;
}
