// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNlbServerGroups(args?: GetNlbServerGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetNlbServerGroupsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("alicloud:index/getNlbServerGroups:getNlbServerGroups", {
        "id": args.id,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
        "resourceGroupId": args.resourceGroupId,
        "serverGroupNames": args.serverGroupNames,
        "serverGroupType": args.serverGroupType,
        "status": args.status,
        "tags": args.tags,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNlbServerGroups.
 */
export interface GetNlbServerGroupsArgs {
    id?: string;
    ids?: string[];
    nameRegex?: string;
    outputFile?: string;
    resourceGroupId?: string;
    serverGroupNames?: string[];
    serverGroupType?: string;
    status?: string;
    tags?: {[key: string]: string};
}

/**
 * A collection of values returned by getNlbServerGroups.
 */
export interface GetNlbServerGroupsResult {
    readonly groups: outputs.GetNlbServerGroupsGroup[];
    readonly id: string;
    readonly ids: string[];
    readonly nameRegex?: string;
    readonly names: string[];
    readonly outputFile?: string;
    readonly resourceGroupId?: string;
    readonly serverGroupNames?: string[];
    readonly serverGroupType?: string;
    readonly status?: string;
    readonly tags?: {[key: string]: string};
}
export function getNlbServerGroupsOutput(args?: GetNlbServerGroupsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNlbServerGroupsResult> {
    return pulumi.output(args).apply((a: any) => getNlbServerGroups(a, opts))
}

/**
 * A collection of arguments for invoking getNlbServerGroups.
 */
export interface GetNlbServerGroupsOutputArgs {
    id?: pulumi.Input<string>;
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    nameRegex?: pulumi.Input<string>;
    outputFile?: pulumi.Input<string>;
    resourceGroupId?: pulumi.Input<string>;
    serverGroupNames?: pulumi.Input<pulumi.Input<string>[]>;
    serverGroupType?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
