// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ImsOidcProvider extends pulumi.CustomResource {
    /**
     * Get an existing ImsOidcProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImsOidcProviderState, opts?: pulumi.CustomResourceOptions): ImsOidcProvider {
        return new ImsOidcProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'alicloud:index/imsOidcProvider:ImsOidcProvider';

    /**
     * Returns true if the given object is an instance of ImsOidcProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImsOidcProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImsOidcProvider.__pulumiType;
    }

    public readonly clientIds!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly createTime!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly fingerprints!: pulumi.Output<string[] | undefined>;
    public readonly issuanceLimitTime!: pulumi.Output<number>;
    public readonly issuerUrl!: pulumi.Output<string>;
    public readonly oidcProviderName!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.ImsOidcProviderTimeouts | undefined>;

    /**
     * Create a ImsOidcProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImsOidcProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImsOidcProviderArgs | ImsOidcProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImsOidcProviderState | undefined;
            resourceInputs["clientIds"] = state ? state.clientIds : undefined;
            resourceInputs["createTime"] = state ? state.createTime : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["fingerprints"] = state ? state.fingerprints : undefined;
            resourceInputs["issuanceLimitTime"] = state ? state.issuanceLimitTime : undefined;
            resourceInputs["issuerUrl"] = state ? state.issuerUrl : undefined;
            resourceInputs["oidcProviderName"] = state ? state.oidcProviderName : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as ImsOidcProviderArgs | undefined;
            if ((!args || args.issuerUrl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'issuerUrl'");
            }
            if ((!args || args.oidcProviderName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'oidcProviderName'");
            }
            resourceInputs["clientIds"] = args ? args.clientIds : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["fingerprints"] = args ? args.fingerprints : undefined;
            resourceInputs["issuanceLimitTime"] = args ? args.issuanceLimitTime : undefined;
            resourceInputs["issuerUrl"] = args ? args.issuerUrl : undefined;
            resourceInputs["oidcProviderName"] = args ? args.oidcProviderName : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["createTime"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ImsOidcProvider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ImsOidcProvider resources.
 */
export interface ImsOidcProviderState {
    clientIds?: pulumi.Input<pulumi.Input<string>[]>;
    createTime?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    fingerprints?: pulumi.Input<pulumi.Input<string>[]>;
    issuanceLimitTime?: pulumi.Input<number>;
    issuerUrl?: pulumi.Input<string>;
    oidcProviderName?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.ImsOidcProviderTimeouts>;
}

/**
 * The set of arguments for constructing a ImsOidcProvider resource.
 */
export interface ImsOidcProviderArgs {
    clientIds?: pulumi.Input<pulumi.Input<string>[]>;
    description?: pulumi.Input<string>;
    fingerprints?: pulumi.Input<pulumi.Input<string>[]>;
    issuanceLimitTime?: pulumi.Input<number>;
    issuerUrl: pulumi.Input<string>;
    oidcProviderName: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.ImsOidcProviderTimeouts>;
}
