// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class KmsNetworkRule extends pulumi.CustomResource {
    /**
     * Get an existing KmsNetworkRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KmsNetworkRuleState, opts?: pulumi.CustomResourceOptions): KmsNetworkRule {
        return new KmsNetworkRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'alicloud:index/kmsNetworkRule:KmsNetworkRule';

    /**
     * Returns true if the given object is an instance of KmsNetworkRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KmsNetworkRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KmsNetworkRule.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public readonly networkRuleName!: pulumi.Output<string>;
    public readonly sourcePrivateIps!: pulumi.Output<string[]>;
    public readonly timeouts!: pulumi.Output<outputs.KmsNetworkRuleTimeouts | undefined>;

    /**
     * Create a KmsNetworkRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KmsNetworkRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KmsNetworkRuleArgs | KmsNetworkRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KmsNetworkRuleState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["networkRuleName"] = state ? state.networkRuleName : undefined;
            resourceInputs["sourcePrivateIps"] = state ? state.sourcePrivateIps : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as KmsNetworkRuleArgs | undefined;
            if ((!args || args.sourcePrivateIps === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sourcePrivateIps'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["networkRuleName"] = args ? args.networkRuleName : undefined;
            resourceInputs["sourcePrivateIps"] = args ? args.sourcePrivateIps : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KmsNetworkRule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering KmsNetworkRule resources.
 */
export interface KmsNetworkRuleState {
    description?: pulumi.Input<string>;
    networkRuleName?: pulumi.Input<string>;
    sourcePrivateIps?: pulumi.Input<pulumi.Input<string>[]>;
    timeouts?: pulumi.Input<inputs.KmsNetworkRuleTimeouts>;
}

/**
 * The set of arguments for constructing a KmsNetworkRule resource.
 */
export interface KmsNetworkRuleArgs {
    description?: pulumi.Input<string>;
    networkRuleName?: pulumi.Input<string>;
    sourcePrivateIps: pulumi.Input<pulumi.Input<string>[]>;
    timeouts?: pulumi.Input<inputs.KmsNetworkRuleTimeouts>;
}
