// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getConsentDefinitionLocalizations(args: GetConsentDefinitionLocalizationsArgs, opts?: pulumi.InvokeOptions): Promise<GetConsentDefinitionLocalizationsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pingdirectory:index/getConsentDefinitionLocalizations:getConsentDefinitionLocalizations", {
        "consentDefinitionName": args.consentDefinitionName,
        "filter": args.filter,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getConsentDefinitionLocalizations.
 */
export interface GetConsentDefinitionLocalizationsArgs {
    consentDefinitionName: string;
    filter?: string;
}

/**
 * A collection of values returned by getConsentDefinitionLocalizations.
 */
export interface GetConsentDefinitionLocalizationsResult {
    readonly consentDefinitionName: string;
    readonly filter?: string;
    readonly id: string;
    readonly ids: string[];
}
export function getConsentDefinitionLocalizationsOutput(args: GetConsentDefinitionLocalizationsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetConsentDefinitionLocalizationsResult> {
    return pulumi.output(args).apply((a: any) => getConsentDefinitionLocalizations(a, opts))
}

/**
 * A collection of arguments for invoking getConsentDefinitionLocalizations.
 */
export interface GetConsentDefinitionLocalizationsOutputArgs {
    consentDefinitionName: pulumi.Input<string>;
    filter?: pulumi.Input<string>;
}
