// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDbbrainDbSpaceStatus(args: GetDbbrainDbSpaceStatusArgs, opts?: pulumi.InvokeOptions): Promise<GetDbbrainDbSpaceStatusResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:index/getDbbrainDbSpaceStatus:getDbbrainDbSpaceStatus", {
        "id": args.id,
        "instanceId": args.instanceId,
        "product": args.product,
        "rangeDays": args.rangeDays,
        "resultOutputFile": args.resultOutputFile,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDbbrainDbSpaceStatus.
 */
export interface GetDbbrainDbSpaceStatusArgs {
    id?: string;
    instanceId: string;
    product?: string;
    rangeDays?: number;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getDbbrainDbSpaceStatus.
 */
export interface GetDbbrainDbSpaceStatusResult {
    readonly availableDays: number;
    readonly growth: number;
    readonly id: string;
    readonly instanceId: string;
    readonly product?: string;
    readonly rangeDays?: number;
    readonly remain: number;
    readonly resultOutputFile?: string;
    readonly total: number;
}
export function getDbbrainDbSpaceStatusOutput(args: GetDbbrainDbSpaceStatusOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDbbrainDbSpaceStatusResult> {
    return pulumi.output(args).apply((a: any) => getDbbrainDbSpaceStatus(a, opts))
}

/**
 * A collection of arguments for invoking getDbbrainDbSpaceStatus.
 */
export interface GetDbbrainDbSpaceStatusOutputArgs {
    id?: pulumi.Input<string>;
    instanceId: pulumi.Input<string>;
    product?: pulumi.Input<string>;
    rangeDays?: pulumi.Input<number>;
    resultOutputFile?: pulumi.Input<string>;
}
