// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEbBus(args?: GetEbBusArgs, opts?: pulumi.InvokeOptions): Promise<GetEbBusResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tencentcloud:index/getEbBus:getEbBus", {
        "filters": args.filters,
        "id": args.id,
        "order": args.order,
        "orderBy": args.orderBy,
        "resultOutputFile": args.resultOutputFile,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEbBus.
 */
export interface GetEbBusArgs {
    filters?: inputs.GetEbBusFilter[];
    id?: string;
    order?: string;
    orderBy?: string;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getEbBus.
 */
export interface GetEbBusResult {
    readonly eventBuses: outputs.GetEbBusEventBus[];
    readonly filters?: outputs.GetEbBusFilter[];
    readonly id: string;
    readonly order?: string;
    readonly orderBy?: string;
    readonly resultOutputFile?: string;
}
export function getEbBusOutput(args?: GetEbBusOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetEbBusResult> {
    return pulumi.output(args).apply((a: any) => getEbBus(a, opts))
}

/**
 * A collection of arguments for invoking getEbBus.
 */
export interface GetEbBusOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetEbBusFilterArgs>[]>;
    id?: pulumi.Input<string>;
    order?: pulumi.Input<string>;
    orderBy?: pulumi.Input<string>;
    resultOutputFile?: pulumi.Input<string>;
}
