// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class PtsProject extends pulumi.CustomResource {
    /**
     * Get an existing PtsProject resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PtsProjectState, opts?: pulumi.CustomResourceOptions): PtsProject {
        return new PtsProject(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:index/ptsProject:PtsProject';

    /**
     * Returns true if the given object is an instance of PtsProject.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PtsProject {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PtsProject.__pulumiType;
    }

    /**
     * App ID.
     */
    public /*out*/ readonly appId!: pulumi.Output<number>;
    /**
     * Creation time.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Pts object description.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * ptsObjectName, which must be required.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Project status.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Sub-user ID.
     */
    public /*out*/ readonly subAccountUin!: pulumi.Output<string>;
    /**
     * Tags List.
     */
    public readonly tags!: pulumi.Output<outputs.PtsProjectTag[] | undefined>;
    /**
     * User ID.
     */
    public /*out*/ readonly uin!: pulumi.Output<string>;
    /**
     * Update time.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a PtsProject resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PtsProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PtsProjectArgs | PtsProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PtsProjectState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["subAccountUin"] = state ? state.subAccountUin : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["uin"] = state ? state.uin : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as PtsProjectArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["appId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["subAccountUin"] = undefined /*out*/;
            resourceInputs["uin"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PtsProject.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PtsProject resources.
 */
export interface PtsProjectState {
    /**
     * App ID.
     */
    appId?: pulumi.Input<number>;
    /**
     * Creation time.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Pts object description.
     */
    description?: pulumi.Input<string>;
    /**
     * ptsObjectName, which must be required.
     */
    name?: pulumi.Input<string>;
    /**
     * Project status.
     */
    status?: pulumi.Input<string>;
    /**
     * Sub-user ID.
     */
    subAccountUin?: pulumi.Input<string>;
    /**
     * Tags List.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.PtsProjectTag>[]>;
    /**
     * User ID.
     */
    uin?: pulumi.Input<string>;
    /**
     * Update time.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PtsProject resource.
 */
export interface PtsProjectArgs {
    /**
     * Pts object description.
     */
    description?: pulumi.Input<string>;
    /**
     * ptsObjectName, which must be required.
     */
    name?: pulumi.Input<string>;
    /**
     * Tags List.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.PtsProjectTag>[]>;
}
